/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dex from "./dex";
export { ILinkableSBT__factory } from "./ILinkableSBT__factory";
export { ISoulName__factory } from "./ISoulName__factory";
export { ISoulboundIdentity__factory } from "./ISoulboundIdentity__factory";
