/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sbt from './SBT';
export type { sbt };
export type { MasaSBT } from './MasaSBT';
export type { MasaSBTAuthority } from './MasaSBTAuthority';
export type { MasaSBTSelfSovereign } from './MasaSBTSelfSovereign';
