/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as masaContractsIdentity from './masa-contracts-identity';
export type { masaContractsIdentity };
