/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PokeSSSBT } from "./PokeSSSBT";
export type { TestASBT } from "./TestASBT";
export type { TestSSSBT } from "./TestSSSBT";
