/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dex from './dex';
export type { dex };
export type { ILinkableSBT } from './ILinkableSBT';
export type { ISoulName } from './ISoulName';
export type { ISoulboundIdentity } from './ISoulboundIdentity';
