name: Build and Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build, lint, and test on Node
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '18'

      - name: Install deps
        run: yarn --frozen-lockfile --network-timeout 1000000000

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
