name: Build and Test

on: [ push ]

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [ '12.x', '14.x', '16.x' ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - name: Fix Windows
        if: matrix.os == 'windows-latest'
        run: |
          npm config set msvs_version 2017
          npm install --global --production windows-build-tools@4.0.0

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
