name: Build and Test

on: [ push ]

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      matrix:
        node: [ '14.x', '16.x', '18.x' ]
        os: [ ubuntu-latest, windows-2019, macOS-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}

      - name: Install deps
        run: yarn --frozen-lockfile --network-timeout 1000000000

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
