name: CI
on: [ push ]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '12.x', '14.x', '16.x' ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - name: Fix Windows
        if: matrix.os == 'windows-latest'
        run: yarn global install windows-build-tools

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1

      - name: Install deps and build (with cache)
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
